
package views;

import conexion.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class BoletaMembresia extends javax.swing.JInternalFrame {

   Conexion enlace = new Conexion();
   Connection conet = enlace.conectar();
    public BoletaMembresia() {
        initComponents();
         this.setLocation(350, 200);   
    mostrarDatosM(0,null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboOpcion = new javax.swing.JComboBox<>();
        campoBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaBoletaM = new javax.swing.JTable();

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar por"));

        comboOpcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mostrar Todos", "Membresia", "Precio", " ", " ", " " }));
        comboOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOpcionActionPerformed(evt);
            }
        });

        campoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBuscarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(comboOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 260, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        tablaBoletaM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaBoletaM.setName(""); // NOI18N
        tablaBoletaM.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tablaBoletaMAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tablaBoletaM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 279, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(74, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOpcionActionPerformed
        int opcion  = comboOpcion.getSelectedIndex();
        String valorbuscado  = campoBuscar.getText();
        mostrarDatosM(opcion,valorbuscado);

    }//GEN-LAST:event_comboOpcionActionPerformed

    private void campoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int opcion  = comboOpcion.getSelectedIndex();
        String valorbuscado  = campoBuscar.getText();
        mostrarDatosM(opcion,valorbuscado);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tablaBoletaMAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tablaBoletaMAncestorAdded

    }//GEN-LAST:event_tablaBoletaMAncestorAdded
public void mostrarDatosM(int opbuscar, String valor) {
    DefaultTableModel tboletaM = new DefaultTableModel(
        new String[]{"id_boleta", "fecha_inicio", "fecha_final", "id_membresia", "dni_c", "Membresia"}, 0
    );
    tablaBoletaM.setModel(tboletaM);

    String codsql;

    if (opbuscar == 0 && valor == null) {
        codsql = "SELECT " +
                 "b.id_boleta, " +
                 "b.fecha_inicio, " +
                 "b.fecha_final, " +
                 "b.id_membresia, " +
                 "b.dni_c, " +
                 "m.tipo_membresia AS Membresia " +
                 "FROM boleta_membresia b " +
                 "JOIN membresia m ON b.id_membresia = m.id_membresia";
    } else if (opbuscar == 1 && valor != null) {
        codsql = "SELECT " +
                 "b.id_boleta, " +
                 "b.fecha_inicio, " +
                 "b.fecha_final, " +
                 "b.id_membresia, " +
                 "b.dni_c, " +
                 "m.tipo_membresia AS Membresia " +
                 "FROM boleta_membresia b " +
                 "JOIN membresia m ON b.id_membresia = m.id_membresia " +
                 "JOIN cliente c ON b.dni_c = c.dni_c " +
                 "WHERE m.tipo_membresia = '" + valor + "'";
    } else if (opbuscar == 2 && valor != null) {
        codsql = "SELECT " +
                 "b.id_boleta, " +
                 "b.fecha_inicio, " +
                 "b.fecha_final, " +
                 "b.id_membresia, " +
                 "b.dni_c, " +
                 "m.tipo_membresia AS Membresia " +
                 "FROM boleta_membresia b " +
                 "JOIN membresia m ON b.id_membresia = m.id_membresia " +
                 "WHERE b.dni_c = '" + valor + "'";
    } else {
    codsql = "SELECT " +
             "b.id_boleta, " +
             "b.fecha_inicio, " +
             "b.fecha_final, " +
             "b.id_membresia, " +
             "b.dni_c, " +
             "m.tipo_membresia AS Membresia " +
             "FROM boleta_membresia b " +
             "JOIN membresia m ON b.id_membresia = m.id_membresia";
}

    if (conet == null) {
        JOptionPane.showMessageDialog(null, "Error en la conexión con la base de datos");
        return;
    }

    try {
        Statement leer = conet.createStatement();
        ResultSet resultado = leer.executeQuery(codsql);

        while (resultado.next()) {
            String[] datos = new String[6];  // Aseguramos que hay 6 columnas
            datos[0] = resultado.getString("id_boleta");
            datos[1] = resultado.getString("fecha_inicio");
            datos[2] = resultado.getString("fecha_final");
            datos[3] = resultado.getString("id_membresia");
            datos[4] = resultado.getString("dni_c");
            datos[5] = resultado.getString("Membresia"); // Usamos el alias explícito

            tboletaM.addRow(datos);
        }

        tablaBoletaM.setModel(tboletaM);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error en la consulta: " + e.getMessage());
    }
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JTextField campoBuscar;
    private javax.swing.JComboBox<String> comboOpcion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaBoletaM;
    // End of variables declaration//GEN-END:variables
}
