/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

import conexion.Conexion;
import controllers.ControllerVoletaM;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.BoletaM;

/**
 *
 * @author user
 */
public class RegistrarVoletaM extends javax.swing.JInternalFrame {
      public int idMembresiaGlobal = 0;
          Conexion enlace = new Conexion();
   Connection conet = enlace.conectar();
    public RegistrarVoletaM() {
        initComponents();
        cargarTodasLasMembresias();
        mostrarDatosBoleta(0,null);
          this.setLocation(500, 100);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFecha2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cb_mem = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtFecha3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSeccion = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        comboOpcion = new javax.swing.JComboBox<>();
        campoBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel12.setText("Registrar Boleta Membresia");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jLabel2.setText("Fecha de fin");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 170, -1));

        jLabel3.setText("Fecha de Inicio");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txtFecha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFecha2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtFecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 170, -1));

        jLabel13.setText("Membresia :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        cb_mem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la Membresia", " ", " " }));
        cb_mem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_memActionPerformed(evt);
            }
        });
        getContentPane().add(cb_mem, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 150, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Cliente");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, -1));

        txtFecha3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFecha3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtFecha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 170, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-disk-96.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel10.setText("Registrar Seccion");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-eliminar-96.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        jLabel14.setText("Elimar seccion");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        jLabel11.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel11.setText("Boletas Registradas");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        tablaSeccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaSeccion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 720, 300));

        comboOpcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mostrar todo", "Por Entrenador", "Por Cliente" }));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-buscar-16.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(comboOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(campoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 261, 720, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void txtFecha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFecha2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFecha2ActionPerformed

    private void cb_memActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_memActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_memActionPerformed

    private void txtFecha3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFecha3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFecha3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// Instanciamos el controlador y el modelo
ControllerVoletaM controlBoleta = new ControllerVoletaM();
BoletaM boleta = new BoletaM();

// Asignamos datos desde los campos de texto
boleta.setFecha_inicio(txtFecha2.getText().trim());
boleta.setFecha_final(txtFecha3.getText().trim());
  this.metodoIDMembresia();
  boleta.setId_membresia(idMembresiaGlobal);
boleta.setDni_c(Integer.parseInt(txtFecha.getText().trim()));

// Intentamos guardar la boleta
if (controlBoleta.guardarBoletaMembresia(boleta)) {
    JOptionPane.showMessageDialog(null, "¡Registro de boleta exitoso!");
} else {
    JOptionPane.showMessageDialog(null, "¡Error al guardar boleta!", "Error", JOptionPane.ERROR_MESSAGE);
}

// Ahora listamos los datos en la tabla después de guardar
DefaultTableModel tboleta = new DefaultTableModel(
    new String[]{"ID", "Fecha Inicio", "Fecha Final", "ID Membresía", "DNI Cliente"}, 0
);
tablaSeccion.setModel(tboleta);

// Conexión
Connection conet = Conexion.conectar();
if (conet == null) {
    JOptionPane.showMessageDialog(null, "Error en la conexión con la base de datos");
    return;
}

// Cargamos los datos en la tabla
String[] datos = new String[5];

try {
    Statement leer = conet.createStatement();
    ResultSet rs = leer.executeQuery("SELECT * FROM boleta_membresia");

    while (rs.next()) {
        datos[0] = rs.getString("id_boleta");
        datos[1] = rs.getString("fecha_inicio");
        datos[2] = rs.getString("fecha_final");
        datos[3] = rs.getString("id_membresia");
        datos[4] = rs.getString("dni_c");
        tboleta.addRow(datos);
    }

    tablaSeccion.setModel(tboleta);
    conet.close();
} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Error al cargar boletas: " + e.getMessage());
}
    }//GEN-LAST:event_jButton1ActionPerformed

    
     public void metodoIDMembresia(){
        //Llamamos a la conexion
        Connection cn = Conexion.conectar();
        String sql = "select id_membresia from membresia where tipo_membresia  = '"+cb_mem.getSelectedItem()+"'";
        Statement st;
        try{
             //Ejecutamos el Statement (sentencia)
            st = cn.createStatement();
            //"Conjuto de resultado" Obtenemos los datos de la BD;
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){  
                idMembresiaGlobal = rs.getInt("id_membresia");
            }
        }catch(SQLException e){
            System.out.println("Error al llamar sus ID de la membresia"+e);
        }
     }
        public void cargarTodasLasMembresias(){
        //Llamamos a la conexion
        Connection cn = Conexion.conectar();
        String sql = "select * from membresia";
        Statement st;
        try{
            //Ejecutamos el Statement (sentencia)
            st = cn.createStatement();
            //"Conjuto de resultado" Obtenemos los datos de la BD;
            ResultSet rs = st.executeQuery(sql);
            cb_mem.removeAllItems(); //Elimina todos los item creados anteriormente
            cb_mem.addItem("Seleccione una Membresia"); //agrego un nuevo item
            //El bucle busca la siguiente fila del ResultSet mientras haya datos
            while(rs.next()){  
                //Almaceno en mi combo box categoria, todos los datos de la tabla categoria
                // pongo "descripcion" porque asi esta el atributo en mi tabla tb_categoria
                cb_mem.addItem(rs.getString("tipo_membresia"));
            }
        }catch(SQLException e){
            System.out.println("Error al cargar Membresia"+e);
        }
    }
    public void mostrarDatosBoleta(int opbuscar, String valor) {
    DefaultTableModel tboleta = new DefaultTableModel(
        new String[]{"ID Boleta", "Fecha Inicio", "Fecha Final", "Tipo Membresía", "Nombre Cliente"}, 0
    );
    tablaSeccion.setModel(tboleta);

    String codsql;

    if (opbuscar == 0 || valor == null) {
        codsql = "SELECT b.id_boleta, b.fecha_inicio, b.fecha_final, m.tipo_membresia, c.nombre " +
                 "FROM boleta_membresia b " +
                 "JOIN membresia m ON b.id_membresia = m.id_membresia " +
                 "JOIN cliente c ON b.dni_c = c.dni_c";
    } else if (opbuscar == 1 && valor != null) {
        codsql = "SELECT b.id_boleta, b.fecha_inicio, b.fecha_final, m.tipo_membresia, c.nombre " +
                 "FROM boleta_membresia b " +
                 "JOIN membresia m ON b.id_membresia = m.id_membresia " +
                 "JOIN cliente c ON b.dni_c = c.dni_c " +
                 "WHERE m.tipo_membresia LIKE '%" + valor + "%'";
    } else if (opbuscar == 2 && valor != null) {
        codsql = "SELECT b.id_boleta, b.fecha_inicio, b.fecha_final, m.tipo_membresia, c.nombre " +
                 "FROM boleta_membresia b " +
                 "JOIN membresia m ON b.id_membresia = m.id_membresia " +
                 "JOIN cliente c ON b.dni_c = c.dni_c " +
                 "WHERE c.nombre LIKE '%" + valor + "%'";
    } else {
        codsql = "SELECT b.id_boleta, b.fecha_inicio, b.fecha_final, m.tipo_membresia, c.nombre " +
                 "FROM boleta_membresia b " +
                 "JOIN membresia m ON b.id_membresia = m.id_membresia " +
                 "JOIN cliente c ON b.dni_c = c.dni_c";
    }

    if (conet == null) {
        JOptionPane.showMessageDialog(null, "Error en la conexión con la base de datos");
        return;
    }

    String[] datos = new String[5];

    try {
        Statement leer = conet.createStatement();
        ResultSet resultado = leer.executeQuery(codsql);

        while (resultado.next()) {
            datos[0] = resultado.getString("id_boleta");
            datos[1] = resultado.getString("fecha_inicio");
            datos[2] = resultado.getString("fecha_final");
            datos[3] = resultado.getString("tipo_membresia");
            datos[4] = resultado.getString("nombre");
            tboleta.addRow(datos);
        }

        tablaSeccion.setModel(tboleta);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error en la consulta: " + e.getMessage());
    }
}

    public void EliminarCliente(){
      int fila = tablaSeccion.getSelectedRow();
      String valor = tablaSeccion.getValueAt(fila, 0).toString();
      
        try {
            PreparedStatement elimi = conet.prepareStatement("delete from boleta_membresia where id_boleta = '"+valor+"'");
                    elimi.executeUpdate();
                    mostrarDatosBoleta(0, null);
        } catch (Exception e) {
        }
    }
   
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        EliminarCliente();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int opcion  = comboOpcion.getSelectedIndex();
        String valorbuscado  = campoBuscar.getText();
        mostrarDatosBoleta(opcion,valorbuscado);
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JTextField campoBuscar;
    private javax.swing.JComboBox<String> cb_mem;
    private javax.swing.JComboBox<String> comboOpcion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaSeccion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtFecha2;
    private javax.swing.JTextField txtFecha3;
    // End of variables declaration//GEN-END:variables
}
