/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

import conexion.Conexion;
import controllers.ControllerSeccion;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Seccion;

/**
 *
 * @author user
 */
public class RegistrarSeccion extends javax.swing.JInternalFrame {

          Conexion enlace = new Conexion();
   Connection conet = enlace.conectar();

    public RegistrarSeccion() {
        initComponents();
         mostrarDatosSeccion(0,null);
          this.setSize(new Dimension(779, 688));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        menuContextual = new javax.swing.JPopupMenu();
        opEliminar = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDni_c = new javax.swing.JTextField();
        txtDni_E = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtDuracion = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSeccion = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        comboOpcion = new javax.swing.JComboBox<>();
        campoBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        jLabel7.setText("jLabel7");

        opEliminar.setText("Eliminar");
        opEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opEliminarActionPerformed(evt);
            }
        });
        menuContextual.add(opEliminar);

        setClosable(true);
        setIconifiable(true);
        setTitle("Registrar seccion");
        setMinimumSize(new java.awt.Dimension(104, 136));
        setPreferredSize(new java.awt.Dimension(779, 688));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setText("Registrar Seccion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jLabel2.setText("Fecha");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel3.setText("Duracion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        jLabel4.setText("DNI Cliente");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jLabel5.setText("DNI Entrenador");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, -1, -1));
        getContentPane().add(txtDni_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 160, -1));
        getContentPane().add(txtDni_E, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 160, -1));

        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 170, -1));
        getContentPane().add(txtDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 170, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-disk-96.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, -1, -1));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 60, -1));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, -1));

        tablaSeccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaSeccion.setComponentPopupMenu(menuContextual);
        jScrollPane1.setViewportView(tablaSeccion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 720, 300));

        jLabel10.setText("Registrar Seccion");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel11.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel11.setText("Secciones Registradas");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-eliminar-96.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        jLabel12.setText("Elimar seccion");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        comboOpcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mostrar todo", "Por Entrenador", "Por Cliente" }));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-buscar-16.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(comboOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(campoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 261, 720, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
    ControllerSeccion controlSeccionP = new ControllerSeccion(); 
    Seccion seccionP = new Seccion();
 
        seccionP.setFecha(txtFecha.getText().trim());
        seccionP.setDuracion(txtDuracion.getText().trim());
        seccionP.setDni_E(Integer.parseInt(txtDni_E.getText().trim()));
        seccionP.setDni_C(Integer.parseInt(txtDni_c.getText().trim()));

        // Intentamos guardar el clien
        if (controlSeccionP.guardarSeccion(seccionP)) {
            JOptionPane.showMessageDialog(null, "¡Registro correcto!");
        } else {
            JOptionPane.showMessageDialog(null, "¡Error al guardar!", "Error", JOptionPane.ERROR_MESSAGE);
        }
         DefaultTableModel tseccion = new DefaultTableModel(
        new String[]{"cod_seccion", "fecha", "duracion", "nombre_cliente", "nombre_entrenador"}, 0
    );
    tablaSeccion.setModel(tseccion);
    if (conet == null) {
        JOptionPane.showMessageDialog(null, "Error en la conexión con la base de datos");
        return;
    }

    String[] datos = new String[5];

    try {
        Statement leer = conet.createStatement();
        ResultSet resultado = leer.executeQuery("SELECT * FROM seccion_entrenamiento");

        while (resultado.next()) {
            datos[0] = resultado.getString("cod_seccion");
            datos[1] = resultado.getString("fecha");
            datos[2] = resultado.getString("duracion");
            datos[3] = resultado.getString("nombre_cliente");
            datos[4] = resultado.getString("nombre_entrenador");
            tseccion.addRow(datos);
        }

        tablaSeccion.setModel(tseccion);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error en la consulta: " + e.getMessage());
    }

        
    }//GEN-LAST:event_jButton1ActionPerformed
  public void mostrarDatosSeccion(int opbuscar, String valor) {
    DefaultTableModel tseccion = new DefaultTableModel(
        new String[]{"cod_seccion", "fecha", "duracion", "nombre_cliente", "nombre_entrenador"}, 0
    );
    tablaSeccion.setModel(tseccion);

    String codsql;

    if (opbuscar == 0 || valor == null ) {
        codsql =  "SELECT s.cod_seccion, s.fecha, s.duracion, c.nombre AS nombre_cliente, e.nombre AS nombre_entrenador " +
                 "FROM seccion_entrenamiento s " +
                 "JOIN cliente c ON s.dni_C = c.dni_C " +
                 "JOIN entrenador e ON s.dni_E = e.dni_E";
    } else if (opbuscar == 1 && valor != null) { 
        // Buscar por nombre del entrenador
        codsql = "SELECT s.cod_seccion, s.fecha, s.duracion, c.nombre AS nombre_cliente, e.nombre AS nombre_entrenador " +
                 "FROM seccion_entrenamiento s " +
                 "JOIN cliente c ON s.dni_C = c.dni_C " +
                 "JOIN entrenador e ON s.dni_E = e.dni_E " +
                 "WHERE e.nombre LIKE '" + valor + "'"; 
    } else if (opbuscar == 2 && valor != null) {  
        // Buscar por nombre del cliente
        codsql = "SELECT s.cod_seccion, s.fecha, s.duracion, c.nombre AS nombre_cliente, e.nombre AS nombre_entrenador " +
                 "FROM seccion_entrenamiento s " +
                 "JOIN cliente c ON s.dni_C = c.dni_C " +
                 "JOIN entrenador e ON s.dni_E = e.dni_E " +
                 "WHERE c.nombre LIKE '" + valor + "'"; 
    } else {
        codsql = "SELECT * FROM seccion_entrenamiento";
    }

    if (conet == null) {
        JOptionPane.showMessageDialog(null, "Error en la conexión con la base de datos");
        return;
    }

    String[] datos = new String[5];

    try {
        Statement leer = conet.createStatement();
        ResultSet resultado = leer.executeQuery(codsql);

        while (resultado.next()) {
            datos[0] = resultado.getString("cod_seccion");
            datos[1] = resultado.getString("fecha");
            datos[2] = resultado.getString("duracion");
            datos[3] = resultado.getString("nombre_cliente");
            datos[4] = resultado.getString("nombre_entrenador");
            tseccion.addRow(datos);
        }

        tablaSeccion.setModel(tseccion);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error en la consulta: " + e.getMessage());
    }
}
    
    public void EliminarCliente(){
      int fila = tablaSeccion.getSelectedRow();
      String valor = tablaSeccion.getValueAt(fila, 0).toString();
      
        try {
            PreparedStatement elimi = conet.prepareStatement("delete from seccion_entrenamiento where cod_seccion = '"+valor+"'");
                    elimi.executeUpdate();
                    mostrarDatosSeccion(0, null);
        } catch (Exception e) {
        }
    }
    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        EliminarCliente();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int opcion  = comboOpcion.getSelectedIndex();
        String valorbuscado  = campoBuscar.getText();
        mostrarDatosSeccion(opcion,valorbuscado);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void opEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opEliminarActionPerformed
        EliminarCliente();
    }//GEN-LAST:event_opEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JTextField campoBuscar;
    private javax.swing.JComboBox<String> comboOpcion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu menuContextual;
    private javax.swing.JMenuItem opEliminar;
    private javax.swing.JTable tablaSeccion;
    private javax.swing.JTextField txtDni_E;
    private javax.swing.JTextField txtDni_c;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtFecha;
    // End of variables declaration//GEN-END:variables
}
