/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;


import conexion.Conexion;
import controllers.ControllerEntrenador;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Entrenador;

/**
 *
 * @author user
 */
public class RegistrarEntrenador1 extends javax.swing.JInternalFrame {

 
       Conexion enlace = new Conexion();
   Connection conet = enlace.conectar();
    public RegistrarEntrenador1() {
        initComponents();
          this.setLocation(250, 70);
          mostrarDatosEntrenador(0,null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuContextual = new javax.swing.JPopupMenu();
        opActualizar = new javax.swing.JMenuItem();
        opEliminar = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        txtexperiencia = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEntrenador = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        comboOpcion = new javax.swing.JComboBox<>();
        campoBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        opActualizar.setText("Actualizar");
        opActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opActualizarActionPerformed(evt);
            }
        });
        menuContextual.add(opActualizar);

        opEliminar.setText("Eliminar");
        opEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opEliminarActionPerformed(evt);
            }
        });
        menuContextual.add(opEliminar);

        setBackground(new java.awt.Color(7, 6, 6));
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel1.setText("Entrenadores Registrados");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        jLabel2.setText("DNI :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel3.setText("Nombre :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel4.setText("Apellido :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel5.setText("Telefono ;");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel6.setText("Email ;");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jLabel7.setText("Direccion :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel8.setText("Experiencia :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        txtDNI.setBackground(new java.awt.Color(255, 255, 255));
        txtDNI.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 175, -1));

        txtnombre.setBackground(new java.awt.Color(255, 255, 255));
        txtnombre.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 175, -1));

        txtapellido.setBackground(new java.awt.Color(255, 255, 255));
        txtapellido.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 175, -1));

        txtTel.setBackground(new java.awt.Color(255, 255, 255));
        txtTel.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 181, -1));

        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 181, -1));

        txtdireccion.setBackground(new java.awt.Color(255, 255, 255));
        txtdireccion.setForeground(new java.awt.Color(0, 0, 0));
        txtdireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdireccionActionPerformed(evt);
            }
        });
        getContentPane().add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 183, -1));

        txtexperiencia.setBackground(new java.awt.Color(255, 255, 255));
        txtexperiencia.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtexperiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 185, -1));

        jButton1.setText("Ingresar Datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, -1, -1));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 110, -1, -1));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, -1, -1));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, -1, -1));

        tablaEntrenador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaEntrenador.setComponentPopupMenu(menuContextual);
        tablaEntrenador.setName(""); // NOI18N
        tablaEntrenador.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tablaEntrenadorAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tablaEntrenador);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 650, 340));

        jButton2.setText("Actualizar datos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, -1, -1));

        jLabel12.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel12.setText("Registrar Entrenador");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 270, 60, -1));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 250, -1, -1));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar por"));

        comboOpcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mostrar Todos", "Identificacion", "Apellido" }));
        comboOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOpcionActionPerformed(evt);
            }
        });

        campoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBuscarActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-buscar-16.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(comboOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 174, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 650, -1));

        jButton3.setText("Eliminar dato");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
    ControllerEntrenador controlEntrenador = new ControllerEntrenador(); 
    Entrenador entrenadorP = new Entrenador(); 
        // Validamos que ningún campo esté vacío antes de continuar
        // Asignamos los valores a la clase Cliente
        entrenadorP.setDni_E(Integer.parseInt(txtDNI.getText().trim()));
        entrenadorP.setNombre(txtnombre.getText().trim());
        entrenadorP.setApellido(txtapellido.getText().trim());
        entrenadorP.setTelefono(txtTel.getText().trim());
        entrenadorP.setEmail(txtEmail.getText().trim());
        entrenadorP.setDireccio(txtdireccion.getText().trim());
        entrenadorP.setExperiencia(txtexperiencia.getText().trim()); // Formato YYYY-MM-DD
   

        // Intentamos guardar el cliente
        if (controlEntrenador.guardarEntrenador(entrenadorP)) {
            JOptionPane.showMessageDialog(null, "¡Registro correcto!");
        } else {
            JOptionPane.showMessageDialog(null, "¡Error al guardar!", "Error", JOptionPane.ERROR_MESSAGE);
        }
               DefaultTableModel tentrenador = new DefaultTableModel(
           new String[]{"dni_E", "nombre", "apellido", "telefono", "email", "direccion", "Experiencia", }, 0
       );
       tablaEntrenador.setModel(tentrenador);        
                             if (conet == null) {
           JOptionPane.showMessageDialog(null, "Error en la conexión con la base de datos");
           return;
       }

       String[] datos = new String[7];

       try {
           Statement leer = conet.createStatement();
           ResultSet resultado = leer.executeQuery("SELECT * FROM entrenador");

           while (resultado.next()) {
               datos[0] = resultado.getString(1);
               datos[1] = resultado.getString(2);
               datos[2] = resultado.getString(3);
               datos[3] = resultado.getString(4);
               datos[4] = resultado.getString(5);
               datos[5] = resultado.getString(6);
               datos[6] = resultado.getString(7);
               tentrenador.addRow(datos);
           }

           tablaEntrenador.setModel(tentrenador);
       } catch (SQLException e) {
           JOptionPane.showMessageDialog(null, "Error en la consulta: " + e.getMessage());
       }                    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablaEntrenadorAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tablaEntrenadorAncestorAdded

    }//GEN-LAST:event_tablaEntrenadorAncestorAdded

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  actualizardatos();      
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void comboOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOpcionActionPerformed
      int opcion  = comboOpcion.getSelectedIndex();
        String valorbuscado  = campoBuscar.getText();
        mostrarDatosEntrenador(opcion,valorbuscado);
        
        
    }//GEN-LAST:event_comboOpcionActionPerformed

    private void campoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int opcion  = comboOpcion.getSelectedIndex();
        String valorbuscado  = campoBuscar.getText();
        mostrarDatosEntrenador(opcion,valorbuscado);

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void opActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opActualizarActionPerformed
        
                actualizardatos();
    }//GEN-LAST:event_opActualizarActionPerformed

    private void opEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opEliminarActionPerformed
       EliminarCliente();


    }//GEN-LAST:event_opEliminarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   EliminarCliente();
    }//GEN-LAST:event_jButton3ActionPerformed

public void mostrarDatosEntrenador(int opbuscar, String valor){

       DefaultTableModel tentrenador = new DefaultTableModel(
           new String[]{"dni_E", "nombre", "apellido", "telefono", "email", "direccion", "Experiencia", }, 0
       );
       tablaEntrenador.setModel(tentrenador);
       
             String codsql;
        if (opbuscar == 0 &&  valor == null ){
         codsql  = "SELECT * FROM entrenador";
        }else {
           if (opbuscar == 1 && valor != null){
           codsql = "select * from entrenador where dni_E = '"+valor+"'" ;
           }else {
           if (opbuscar == 2 && valor != null){
           codsql = "select * from entrenador where apellido = '"+valor+"'" ;
           } else {
               codsql  = "SELECT * FROM entrenador";
           }
           }
        }

       if (conet == null) {
           JOptionPane.showMessageDialog(null, "Error en la conexión con la base de datos");
           return;
       }

       String[] datos = new String[7];

       try {
           Statement leer = conet.createStatement();
           ResultSet resultado = leer.executeQuery(codsql);

           while (resultado.next()) {
               datos[0] = resultado.getString(1);
               datos[1] = resultado.getString(2);
               datos[2] = resultado.getString(3);
               datos[3] = resultado.getString(4);
               datos[4] = resultado.getString(5);
               datos[5] = resultado.getString(6);
               datos[6] = resultado.getString(7);
               tentrenador.addRow(datos);
           }

           tablaEntrenador.setModel(tentrenador);
       } catch (SQLException e) {
           JOptionPane.showMessageDialog(null, "Error en la consulta: " + e.getMessage());
       }
}
 public void actualizardatos(){
    
    int  fila  = tablaEntrenador.getSelectedRow();
    
      if (fila < -1) {
        JOptionPane.showMessageDialog(null, "Seleccione un Entrenador para actualizar.");
        return;
    }
    
    int id  = Integer.parseInt(this.tablaEntrenador.getValueAt(fila, 0).toString());
    String nom = tablaEntrenador.getValueAt(fila, 1).toString();
      String ape = tablaEntrenador.getValueAt(fila, 2).toString();
        String tel = tablaEntrenador.getValueAt(fila, 3).toString();
          String ema = tablaEntrenador.getValueAt(fila, 4).toString();
            String dir = tablaEntrenador.getValueAt(fila, 5).toString();
              String exp = tablaEntrenador.getValueAt(fila, 6).toString();
     
               
        try { 
             PreparedStatement actu  = conet.prepareStatement("update entrenador set nombre = '"+nom+"', apellido  = '"+ape+"',  telefono = '"+tel+"', email ='"+ema+"',  direccion ='"+dir+"', experiencia ='"+exp+"' where dni_e = '"+id+"'  ");
             actu.executeUpdate();
            mostrarDatosEntrenador(0, null);
               
               } catch (Exception e){
               }

    }
    public void EliminarCliente(){
      int fila = tablaEntrenador.getSelectedRow();
      String valor = tablaEntrenador.getValueAt(fila, 0).toString();
      
        try {
            PreparedStatement elimi = conet.prepareStatement("delete from entrenador where dni_e = '"+valor+"'");
                    elimi.executeUpdate();
                    mostrarDatosEntrenador(0, null);
        } catch (Exception e) {
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JTextField campoBuscar;
    private javax.swing.JComboBox<String> comboOpcion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu menuContextual;
    private javax.swing.JMenuItem opActualizar;
    private javax.swing.JMenuItem opEliminar;
    private javax.swing.JTable tablaEntrenador;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtexperiencia;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}

